name: Feature Request
description: Suggest an idea for this project
labels: ["feature"]
assignees:
  - SvenTiigi
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: Yes, the problem is that...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: What solution would you like?
      description: A clear and concise description of what you want to happen.
      placeholder: I would like that...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: What alternatives have you considered?
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I have considered to...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Any additional context?
      description: Add any other context or screenshots about the feature request here.
